substitutions:
  device_name: dolphin-ble
  friendly_name: Dolphin BLE
  dolphin_mac: ""

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: jim.dolphin_ble
    version: "1.0"

dashboard_import:
  package_import_url: github://jimparis/esphome-dolphin-plus/dolphin_ble.yaml@master
  import_full_config: false

wifi:
  ap:

captive_portal:

improv_serial:

esp32_improv:
  authorizer: none

api:

ota:
  - platform: esphome

external_components:
  - source: github://jimparis/esphome-dolphin-plus@master
    components:
      - dolphin_ble

packages:
  dolphin_ble:
    url: https://github.com/jimparis/esphome-dolphin-plus
    files:
      - packages/dolphin_ble.yaml
    ref: master
    refresh: 0s
