esphome:
  name: dolphin-ble
  friendly_name: Dolphin BLE

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_GATTC_ENABLE: y
      CONFIG_BT_GATTS_ENABLE: y

logger:
  level: DEBUG

esp32_ble:
  io_capability: none

external_components:
  - source:
      type: local
      path: components

dolphin_ble:
  mac_address: AC:74:C4:0E:D8:6E
  name_filter: Z4868YMR
  auto_probe: true
  probes:
    - name: pws_features
      text: "03:ab03fffa1a000002c1"
      delay_ms: 5000
    - name: system_status
      text: "03:ab03fff807000002ac"
      delay_ms: 1500
    - name: temperature
      text: "03:ab03fff809000002ae"
      delay_ms: 1500
    - name: cloud_connection_status
      text: "03:ab03fffedf0000038a"
      delay_ms: 1500
    - name: get_mu_data
      text: "03:ab03fffd0100030100ff03ae"
      delay_ms: 2000
    - name: get_sm_data
      text: "03:ab03fffd0200030200ff03b0"
      delay_ms: 2000
