name: Publish Firmware

on:
  push:
    branches:
      - master
    paths:
      - '*.yaml'
      - 'components/**'
      - 'packages/**'
      - 'static/**'
      - '.github/workflows/publish-firmware.yml'
      - '.github/workflows/publish-pages.yml'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@025a1e6255610c498ed590403b7e510b69e474df  # 2026.4.1
    with:
      #### Modify below here to match your project ####
      files: |
        dolphin_ble.yaml
      esphome-version: 2026.6.5
      combined-name: dolphin_ble
